version: "3.3"
services:
  node:
    container_name: node
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo-db
      - crossbar
    links:
      - mongo-db
      - crossbar
  mongo-db:
    container_name: mongo-db
    restart: always
    image: mongo
    ports:
      - "27017:27017"

